DROP TABLE "users_sessions" CASCADE;--> statement-breakpoint
DROP TABLE "website_subscriptions" CASCADE;--> statement-breakpoint
DROP TABLE "website_llm_models" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbots" CASCADE;--> statement-breakpoint
DROP TABLE "users" CASCADE;--> statement-breakpoint
DROP TABLE "users_team_members" CASCADE;--> statement-breakpoint
DROP TABLE "users_invitations" CASCADE;--> statement-breakpoint
DROP TABLE "users_subscriptions" CASCADE;--> statement-breakpoint
DROP TABLE "users_addons_purchased" CASCADE;--> statement-breakpoint
DROP TABLE "website_add_ons" CASCADE;--> statement-breakpoint
DROP TABLE "users_referrals" CASCADE;--> statement-breakpoint
DROP TABLE "website_promotion_referral" CASCADE;--> statement-breakpoint
DROP TABLE "users_rate_limits" CASCADE;--> statement-breakpoint
DROP TABLE "users_llm_model_usage" CASCADE;--> statement-breakpoint
DROP TABLE "users_usage_tracking" CASCADE;--> statement-breakpoint
DROP TABLE "users_billing" CASCADE;--> statement-breakpoint
DROP TABLE "users_api_keys" CASCADE;--> statement-breakpoint
DROP TABLE "users_api_request_logs" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_appearance_ui" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_behavior" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_settings_general" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_chatting_customers" CASCADE;--> statement-breakpoint
DROP TABLE "cache_delete_requests" CASCADE;--> statement-breakpoint
DROP TABLE "ingestion_files" CASCADE;--> statement-breakpoint
DROP TABLE "ingestion_chunks" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_conversation_starters" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_custom_prompts" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_follow_up_prompts" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_settings_instruction" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_personas" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_settings_localization_texts" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_integrations" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_human_support_settings" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_leads_settings" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_threads" CASCADE;--> statement-breakpoint
DROP TABLE "ingestion_status_logs" CASCADE;--> statement-breakpoint
DROP TABLE "ingestion_errors" CASCADE;--> statement-breakpoint
DROP TABLE "ingestion_sources" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_retrieval_runs" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_messages" CASCADE;--> statement-breakpoint
DROP TABLE "user_chatbot_system_errors" CASCADE;